export const SUPABASE_NOT_CONFIGURED = "SUPABASE_NOT_CONFIGURED";
export const SUPABASE_UNAVAILABLE = "SUPABASE_UNAVAILABLE";
export const SUPABASE_AUTH_UNAVAILABLE = "SUPABASE_AUTH_UNAVAILABLE";
export const SUPABASE_AUTH_LINK_MISSING = "SUPABASE_AUTH_LINK_MISSING";

export type SupabaseHealthState =
  | typeof SUPABASE_NOT_CONFIGURED
  | typeof SUPABASE_UNAVAILABLE
  | typeof SUPABASE_AUTH_UNAVAILABLE
  | typeof SUPABASE_AUTH_LINK_MISSING
  | "CONFIGURED";
